In [2]:
import librosa
import librosa.display
import IPython.display as ipd
import os
from sklearn import svm
import numpy as np

In [3]:
for file in os.listdir('../audio_data/'):
    print(file)

dash.wav
dot.wav


In [5]:
for file in os.listdir('../dataset_creation/output_datasets/dash/'):
    print(file)

dataset_10_noise_0.53.wav
dataset_10_pitch_-9.wav
dataset_11_noise_0.57.wav
dataset_11_pitch_-8.wav
dataset_12_noise_0.62.wav
dataset_12_pitch_-2.wav
dataset_13_noise_0.67.wav
dataset_13_pitch_2.wav
dataset_14_noise_0.72.wav
dataset_14_pitch_-5.wav
dataset_15_noise_0.76.wav
dataset_15_pitch_-6.wav
dataset_16_noise_0.81.wav
dataset_16_pitch_5.wav
dataset_17_noise_0.86.wav
dataset_17_pitch_7.wav
dataset_18_noise_0.91.wav
dataset_18_pitch_5.wav
dataset_19_noise_0.95.wav
dataset_19_pitch_-7.wav
dataset_1_noise_0.10.wav
dataset_1_pitch_10.wav
dataset_20_noise_1.00.wav
dataset_20_pitch_1.wav
dataset_2_noise_0.15.wav
dataset_2_pitch_10.wav
dataset_3_noise_0.19.wav
dataset_3_pitch_3.wav
dataset_4_noise_0.24.wav
dataset_4_pitch_-4.wav
dataset_5_noise_0.29.wav
dataset_5_pitch_0.wav
dataset_6_noise_0.34.wav
dataset_6_pitch_-9.wav
dataset_7_noise_0.38.wav
dataset_7_pitch_3.wav
dataset_8_noise_0.43.wav
dataset_8_pitch_3.wav
dataset_9_noise_0.48.wav
dataset_9_pitch_6.wav


In [6]:
for file in os.listdir('../dataset_creation/output_datasets/dot/'):
    print(file)

dataset_10_noise_0.53.wav
dataset_10_pitch_2.wav
dataset_11_noise_0.57.wav
dataset_11_pitch_-2.wav
dataset_12_noise_0.62.wav
dataset_12_pitch_3.wav
dataset_13_noise_0.67.wav
dataset_13_pitch_-1.wav
dataset_14_noise_0.72.wav
dataset_14_pitch_-5.wav
dataset_15_noise_0.76.wav
dataset_15_pitch_-3.wav
dataset_16_noise_0.81.wav
dataset_16_pitch_0.wav
dataset_17_noise_0.86.wav
dataset_17_pitch_-1.wav
dataset_18_noise_0.91.wav
dataset_18_pitch_5.wav
dataset_19_noise_0.95.wav
dataset_19_pitch_10.wav
dataset_1_noise_0.10.wav
dataset_1_pitch_7.wav
dataset_20_noise_1.00.wav
dataset_20_pitch_-5.wav
dataset_2_noise_0.15.wav
dataset_2_pitch_6.wav
dataset_3_noise_0.19.wav
dataset_3_pitch_1.wav
dataset_4_noise_0.24.wav
dataset_4_pitch_8.wav
dataset_5_noise_0.29.wav
dataset_5_pitch_-6.wav
dataset_6_noise_0.34.wav
dataset_6_pitch_6.wav
dataset_7_noise_0.38.wav
dataset_7_pitch_9.wav
dataset_8_noise_0.43.wav
dataset_8_pitch_1.wav
dataset_9_noise_0.48.wav
dataset_9_pitch_-4.wav


In [7]:
ipd.Audio('../audio_data/dash.wav')

In [8]:
ipd.Audio('../audio_data/dot.wav')

In [9]:
def feature_extraction(file_path):
    # load the audio file
    x, sample_rate = librosa.load(file_path, res_type='kaiser_fast')
    # extract features from the audio
    mfcc = np.mean(librosa.feature.mfcc(y=x, sr=sample_rate, n_mfcc=50).T, axis=0)
    
    return mfcc

In [10]:
features = {}
original_directory = '../audio_data/'
directory1 = '../dataset_creation/output_datasets/dash/'
directory2 = '../dataset_creation/output_datasets/dot/'

for audio in os.listdir(original_directory):
    audio_path = original_directory+audio
    print(audio_path)
    features[audio_path] = feature_extraction(audio_path)
for audio in os.listdir(directory1):
    audio_path = directory1+audio
    print(audio_path)
    features[audio_path] = feature_extraction(audio_path)
for audio in os.listdir(directory2):
    audio_path = directory2+audio
    print(audio_path)
    features[audio_path] = feature_extraction(audio_path)

../audio_data/dash.wav
../audio_data/dot.wav
../dataset_creation/output_datasets/dash/dataset_10_noise_0.53.wav
../dataset_creation/output_datasets/dash/dataset_10_pitch_-9.wav
../dataset_creation/output_datasets/dash/dataset_11_noise_0.57.wav
../dataset_creation/output_datasets/dash/dataset_11_pitch_-8.wav
../dataset_creation/output_datasets/dash/dataset_12_noise_0.62.wav
../dataset_creation/output_datasets/dash/dataset_12_pitch_-2.wav
../dataset_creation/output_datasets/dash/dataset_13_noise_0.67.wav
../dataset_creation/output_datasets/dash/dataset_13_pitch_2.wav
../dataset_creation/output_datasets/dash/dataset_14_noise_0.72.wav
../dataset_creation/output_datasets/dash/dataset_14_pitch_-5.wav
../dataset_creation/output_datasets/dash/dataset_15_noise_0.76.wav
../dataset_creation/output_datasets/dash/dataset_15_pitch_-6.wav
../dataset_creation/output_datasets/dash/dataset_16_noise_0.81.wav
../dataset_creation/output_datasets/dash/dataset_16_pitch_5.wav
../dataset_creation/output_datase

In [11]:
audio_path = '../audio_data/dash.wav'
features[audio_path], len(features[audio_path])

(array([-3.5070670e+02, -4.6999077e+01, -8.6100777e+01,  1.8460558e+01,
         3.7931400e+01,  8.6805534e+00, -1.9752041e+01, -1.0860295e+01,
        -1.8172287e+00,  2.5190765e+01, -5.8038082e+00, -7.3108077e+00,
        -5.9318452e+00,  7.7757654e+00, -3.3723686e+00,  4.2013783e+00,
        -2.5796993e+00,  1.6210191e+00, -1.4725769e+01, -2.6844752e+00,
         9.1466351e+00,  4.1496515e+00, -6.8267913e+00,  5.0584040e+00,
        -2.4602673e+00,  1.6604389e+01, -1.3309797e+01,  8.0787592e+00,
        -1.0052483e+00,  2.0528093e+01, -1.0409021e+01,  6.9951682e+00,
        -3.6942368e+00,  6.5883646e+00, -4.0328503e+00,  5.7142177e+00,
        -2.0205219e+00,  9.7721272e+00, -3.3209107e+00, -4.3956809e+00,
         1.4367306e+00,  2.1704569e+00, -2.3482065e+00, -5.5667424e+00,
         1.3900002e+00,  8.5102397e-01,  9.5186317e-01,  3.2560247e-01,
        -4.3805504e+00,  4.5993314e+00], dtype=float32),
 50)

In [12]:
audio_path = '../audio_data/dot.wav'
features[audio_path], len(features[audio_path])

(array([-1.86687729e+02,  3.33707695e+01, -4.37620926e+01,  4.83768539e+01,
         4.14167976e+01, -1.37656584e+01, -1.94596958e+01, -5.50670004e+00,
         4.52979279e+00, -1.41200771e+01, -3.71360397e+01,  1.20103893e+01,
         1.05542374e+01,  2.21899295e+00, -1.85990162e+01, -1.38127208e+00,
        -3.82931399e+00,  1.19912195e+01, -2.21763363e+01, -1.68123567e+00,
         8.13854408e+00, -1.59443789e+01, -1.35885258e+01, -4.00953054e+00,
        -1.25604942e-01, -1.02408285e+01, -1.03913221e+01,  6.77153301e+00,
         1.16964664e+01,  1.11714115e+01,  1.31829834e+01,  3.50485001e+01,
         1.61787927e+00,  3.80467415e+00,  1.04388750e+00,  1.02985859e+01,
         4.55979300e+00,  6.15705729e+00, -6.32079077e+00,  5.12616682e+00,
        -7.38087606e+00,  2.49622989e+00, -9.44869995e-01,  2.69129896e+00,
        -7.99297333e+00, -1.80108953e+00, -2.16144896e+00, -3.54828072e+00,
         1.92282033e+00, -3.02499652e+00], dtype=float32),
 50)

In [189]:
# from sklearn import svm   # imported at the start

audio_path = '../audio_data/dash.wav'  # as sound 1
feature_array_dash_org = np.array(features[audio_path])

feature_array_dash_datasets = []
for audio in os.listdir(directory1):
    audio_path = directory1+audio
    feature_array_dash_datasets.append(np.array(features[audio_path]))
    
    
audio_path = '../audio_data/dot.wav'  # as sound 2
feature_array_dot_org = np.array(features[audio_path])

feature_array_dot_datasets = []
for audio in os.listdir(directory2):
    audio_path = directory2+audio
    feature_array_dot_datasets.append(np.array(features[audio_path]))


X_train = np.vstack([feature_array_dash_org, feature_array_dash_datasets, feature_array_dot_org, feature_array_dot_datasets])

# there are 40 samples each + 1 original
y_sound1 = np.zeros(41, dtype=np.int32)  
y_sound2 = np.ones(41, dtype=np.int32)  

y_train = np.concatenate([y_sound1, y_sound2])

# Assuming you have your training data X_train and y_train from the previous example
# Initialize SVM classifier
classifier = svm.SVC(kernel='linear')

# Train the classifier (assuming X_train and y_train are available)
classifier.fit(X_train, y_train)



SVC(kernel='linear')

In [188]:
# # FOR ACCURACY TESTING, LET IT BE COMMENTED

# # Import necessary libraries
# from sklearn.metrics import accuracy_score
# from sklearn.model_selection import train_test_split

# # Split the data into training and test sets
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
# # print(X_test)
# # print(y_test)

# # Initialize SVM classifier
# classifier = svm.SVC(kernel='linear')

# # Train the classifier
# classifier.fit(X_train, y_train)

# # Predict labels for training and test sets
# y_train_pred = classifier.predict(X_train)
# y_test_pred = classifier.predict(X_test)
# print(y_test)
# print (y_test_pred)

# # Calculate training and test accuracies
# train_accuracy = accuracy_score(y_train, y_train_pred)
# test_accuracy = accuracy_score(y_test, y_test_pred)

# print("Training Accuracy:", train_accuracy)
# print("Test Accuracy:", test_accuracy)


[0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1]
[0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1]
Training Accuracy: 1.0
Test Accuracy: 0.8823529411764706


In [198]:
# input_audio = '../input test files/dot_test_file.wav'
# input_audio = '../input test files/dot_copy.wav'
# input_audio = '../input test files/dash_copy.wav'

import os
import random 

def get_random_file(directory):
    files = os.listdir(directory)
    if files:
        return os.path.join(directory, random.choice(files))
    else:
        return None

# random_file_set = []
# for i in range (5):
#     random_file = get_random_file(directory1)  
#     random_file_set.append(random_file)
#     random_file = get_random_file(directory2)  
#     random_file_set.append(random_file)
    
# for audio_path in random_file_set:
#     print(audio_path)

# feature_array_new = []
# for audio_path in random_file_set:
#     feature_array_new.append(np.array(features[audio_path]))

# X_new = np.vstack([feature_array_new])

    
input_file_set = []
input_test_directory = '../input test files/'
for audio in os.listdir(input_test_directory):
    audio_path = input_test_directory+audio
    print(audio_path)
    input_file_set.append(audio_path)
    features[audio_path] = feature_extraction(audio_path)


feature_array_new = []
for audio_path in input_file_set:
    feature_array_new.append(np.array(features[audio_path]))

X_new = np.vstack([feature_array_new])


# random_file = get_random_file(directory1)  
# random_file = get_random_file(directory2)  

# if random_file:
#     print("Random file:", random_file)
# else:
#     print("No files found in the directory.")

# input_features = feature_extraction(audio_path)

# input_features_array = np.array(input_features)

# X_new = np.vstack([input_features_array])


../input test files/dash_copy.wav
../input test files/dot_copy.wav
../input test files/dot_test_file.wav


In [199]:
# print(X_new)
# Reshape the feature array to be a 2D array with a single row
# X_new_reshaped = X_new.reshape(1, -1)  # just in case, actually not required
# print(X_new_reshaped)

# Predict the class of the provided feature array
train_prediction = classifier.predict(X_train)
prediction = classifier.predict(X_new)

print(train_prediction)
print(prediction)
# # Map the prediction to the corresponding sound class
# if prediction[0] == 0:
#     print("Input sound is dash")  # dash
# elif prediction[0] == 1:
#     print("Input sound is dot")  # dot
# else:
#     print("Unknown sound")


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]
[0 1 1]


In [22]:
# ipd.Audio('input test files/dot_test_file.wav')
# ipd.Audio('input test files/dot_copy.wav')
ipd.Audio('../input test files/dash_copy.wav')